usr/share/backgrounds/160218-deux-two_by_Pierre_Cante.jpg
usr/share/backgrounds/Black_hole_by_Marek_Koteluk.jpg
usr/share/backgrounds/Cielo_estrellado_by_Eduardo_Diez_Viñuela.jpg
usr/share/backgrounds/clock_by_Bernhard_Hanakam.jpg
usr/share/backgrounds/Dans_ma_bulle_by_Christophe_Weibel.jpg
usr/share/backgrounds/Flora_by_Marek_Koteluk.jpg
usr/share/backgrounds/Icy_Grass_by_Raymond_Lavoie.jpg
usr/share/backgrounds/Night_lights_by_Alberto_Salvia_Novella.jpg
usr/share/backgrounds/passion_flower_by_Irene_Gr.jpg
usr/share/backgrounds/Spring_by_Peter_Apas.jpg
usr/share/backgrounds/TCP118v1_by_Tiziano_Consonni.jpg
usr/share/backgrounds/The_Land_of_Edonias_by_*
usr/share/backgrounds/Xerus_Wallpaper_Grey_4096x2304.png
usr/share/backgrounds/contest/xenial.xml
usr/share/gnome-background-properties/xenial-wallpapers.xml

