usr/share/backgrounds/Focal-Fossa_WP_4096x2304_GREY.png
usr/share/backgrounds/brad-huchteman-stone-mountain.jpg
usr/share/backgrounds/joshua-coleman-something-yellow.jpg
usr/share/backgrounds/matt-mcnulty-nyc-2nd-ave.jpg
usr/share/backgrounds/ryan-stone-skykomish-river.jpg
usr/share/backgrounds/hardy_wallpaper_uhd.png
usr/share/gnome-background-properties/focal-wallpapers.xml
usr/share/backgrounds/contest/focal.xml