name: Mirror Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        run: |
          git clone https://$GH_PAT@github.com/twinysam/ubuntu-wallpapers.git repo
          cd repo
          git config --global user.email "twinysam@gmail.com"
          git config --global user.name "twinysam"
          git remote add upstream https://git.launchpad.net/ubuntu/+source/ubuntu-wallpapers
          git fetch upstream
          for branch in $(git branch -r | grep -v '\->' | sed 's/ *upstream\///g'); do
              git checkout -b $branch upstream/$branch || true
          done
          latest_branch=$(git for-each-ref --sort=-committerdate refs/remotes/upstream/ --format='%(refname:short)' | head -n 1 | sed 's|upstream/||')
          echo "latest_branch is $latest_branch"
          echo "latest_branch=$latest_branch" >> $GITHUB_ENV
          git checkout $latest_branch
          git push origin $latest_branch
          git push --mirror origin
        env:
          GH_PAT: ${{ secrets.GH_PAT }}

      - name: Set default branch
        run: |
          latest_branch=${{ env.latest_branch }}
          echo "Setting default branch to $latest_branch"
          curl -X PATCH -H "Authorization: token $GH_PAT" -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/twinysam/ubuntu-wallpapers -d "{\"default_branch\":\"$latest_branch\"}"
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
