name: Mirror Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: ./github/actions/checkout

      - name: Set up Git
        run: |
          cd repo
          git config --global user.email "twinysam@gmail.com"
          git config --global user.name "twinysam"

      - name: Fetch updates from upstream
        run: |
          cd repo
          git remote add upstream https://git.launchpad.net/ubuntu/+source/ubuntu-wallpapers
          git fetch upstream --tags
          latest_branch=$(git for-each-ref --sort=-committerdate refs/remotes/upstream/ --format='%(refname:short)' | head -n 1)
          echo "latest_branch=$latest_branch" >> $GITHUB_ENV
          git checkout ${{ env.latest_branch }}

      - name: Push updates to GitHub mirror
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          cd repo
          git push --mirror origin
