name: Mirror Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        run: |
          git clone https://github.com/twinysam/ubuntu-wallpapers.git repo
          cd repo
          git remote add upstream https://git.launchpad.net/ubuntu/+source/ubuntu-wallpapers
          git fetch upstream --tags
          latest_branch=$(git for-each-ref --sort=-committerdate refs/remotes/upstream/ --format='%(refname:short)' | head -n 1)
          echo "latest_branch=$latest_branch" >> $GITHUB_ENV
          git checkout ${{ env.latest_branch }}
          git push --mirror origin
